config/routes.rb
Rails.application.routes.draw do
  resources :pitches
  resources :pitches
  resources :pitches
  mount Upmin::Engine => '/admin'
  root to: 'pitches#new'
  devise_for :users
  resources :users
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_pitch, only: [:show, :edit, :update, :destroy]

  # GET /pitches
  # GET /pitches.json
  def index
    @pitches = Pitch.all
  end

  # GET /pitches/1
  # GET /pitches/1.json
  def show
  end

  # GET /pitches/new
  def new
    @pitch = Pitch.new
  end

  # GET /pitches/1/edit
  def edit
  end

  # POST /pitches
  # POST /pitches.json
  def create
    @pitch = Pitch.new(pitch_params)

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to @pitch, notice: 'Pitch was successfully created.' }
        format.json { render :show, status: :created, location: @pitch }
      else
        format.html { render :new }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitches/1
  # PATCH/PUT /pitches/1.json
  def update
    respond_to do |format|
      if @pitch.update(pitch_params)
        format.html { redirect_to @pitch, notice: 'Pitch was successfully updated.' }
        format.json { render :show, status: :ok, location: @pitch }
      else
        format.html { render :edit }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitches/1
  # DELETE /pitches/1.json
  def destroy
    @pitch.destroy
    respond_to do |format|
      format.html { redirect_to pitches_url, notice: 'Pitch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitch
      @pitch = Pitch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitch_params
      params.require(:pitch).permit(:story, :solving, :relevance, :personal, :genesis, :solved, :product, :nontech, :traction, :ux, :competitors, :differentiators, :better, :money, :market, :funding, :total, :funding, :moneyusedfor, :investors, :team, :personalstory, :exclusive, :embargo, :contactdetails, :relevantstories, :productvideos, :crunchbase)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/views/layouts/_footer.html.erb
</br>
<!-- Social Footer, Colour Matching Icons -->
<!-- Include Font Awesome Stylesheet in Header -->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<!-- // -->
<div class="container">
  <hr></br>
        <div class="text-center center-block">
         <a href="http://benrmatthews.com/">Built by @benrmatthews,</a><a href="http://montfort.io/"> for Montfort,</a><a href="http://mbites.com/"> with thanks to Mike Butcher.</a></br>

            <br />
	            <a href="https://twitter.com/benrmatthews"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a>
	            <a href="mailto:ben@montfort.io"><i id="social" class="fa fa-envelope-square fa-3x social-em"></i></a>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Pitch Template', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <!-- <li><%= link_to 'Sign in', new_user_session_path %></li> -->
  <!-- <li><%= link_to 'Sign up', new_user_registration_path %></li> -->
<li><%= link_to 'New Pitch', new_pitch_path, class: "btn btn-lg btn-primary" %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pitch Template" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pitch Template" %>">
    <meta name="google-site-verification" content="N7bJIbBRr6ivDUj8jdZxuPA9LgOocIRVdPFjeGiRk6g" />
    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48644120-3', 'auto');
  ga('send', 'pageview');

</script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
      <%= render 'layouts/footer' %>
    </main>
  </body>
</html>

app/views/pitches/_form.html.erb
<%= simple_form_for(@pitch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :story, label: "WHAT IS THE BIG PICTURE HERE? WHAT IS ‘THE STORY’?", hint: "(Max 5 sentences)" %>
    <%= f.input :solving, label: "WHAT IS THE PROBLEM THIS COMPANY IS SOLVING?", hint: "(Max 3 sentences)" %>
    <%= f.input :personal, label: "WAS IT A PERSONAL PROBLEM YOU HAD?", hint: "(Max 5 sentences)" %>
    <%= f.input :genesis, label: "DESCRIBE THE GENESIS OF THE PRODUCT?", hint: "(Max 5 sentences)" %>
    <%= f.input :solved, label: "HOW HAS THIS PRODUCT SOLVED THAT PROBLEM?", hint: "(Max 3 sentences)" %>
    <%= f.input :product, label: "WHAT DOES IT *ACTUALLY* DO?", hint: "(Max 5 sentences)" %>
    <%= f.input :nontech, label: "DESCRIBE IT AS IF YOU WERE DESCRIBING IT TO A NON-TECH PERSON ON THE STREET:", hint: "(Max 3 sentences)" %>
    <%= f.input :relevance, label: "WHAT IS HAPPENING IN THE NEWS RIGHT NOW THAT MAKES YOU RELEVANT?", hint: "(Max 5 sentences)" %>

    <%= f.input :traction, label: "HOW MUCH TRACTION DO YOU HAVE?", hint: "(Real numbers: monthly or daily active users, not downloads or registered, or in your case, transaction volume)" %>
    <%= f.input :ux, label: "OK, NOW WALK ME THROUGH THE USER EXPERIENCE:", hint: "(Max 10 sentences)" %>
    <%= f.input :competitors, label: "WHO ARE THE COMPETITORS?", hint: "(Max 3 sentences)" %>
    <%= f.input :differentiators, label: "WHAT ARE THE KEY DIFFERENTIATORS BETWEEN YOU AND OTHER PLAYERS?", hint: "(Max 5 sentences)" %>
    <%= f.input :better, label: "WHY IS THIS BETTER THAN THOSE OTHER GUYS?", hint: "(Max 3 sentences)" %>
    <%= f.input :money, label: "HOW DO YOU MAKE (OR PLAN TO MAKE) MONEY WITH THIS?", hint: "(Max 3 sentences)" %>
    <%= f.input :market, label: "HOW BIG IS THE MARKET IT IS ADDRESSING?", hint: "(Max 3 sentences)" %>
    <%= f.input :funding, label: "WHAT IS THE NEW ROUND OF FUNDING?", hint: "(Specify Seed, Series A, etc)" %>
    <%= f.input :total, label: "HOW MUCH FUNDING (in $) DOES IT HAVE IN TOTAL?", hint: "" %>
    <%= f.input :moneyusedfor, label: "WHAT WILL THE MONEY BE USED FOR?", hint: "(Be specific!)" %>
    <%= f.input :investors, label: "WHO ARE THE INVESTORS?", hint: "" %>
    <%= f.input :team, label: "WHO IS IN THE TEAM?", hint: "(Max 3 sentences)" %>
    <%= f.input :personalstory, label: "DO THE FOUNDERS HAVE A COMPELLING PERSONAL STORY IN SOME WAY?", hint: "(Max 5 sentences)" %>
    <%= f.input :exclusive, label: "IS THIS STORY EXCLUSIVE TO TECHCRUNCH?", hint: "(Tip: The answer should be yes)" %>
    <%= f.input :embargo, label: "IF NOT, WHEN DOES THE EMBARGO DROP?", hint: "(Tip: Avoid embargoes! Just give me the exclusive)" %>
    <h2>Other Requirements</h2>
    <%= f.input :contactdetails, label: "CONTACT DETAILS FOR FOUNDERS", hint: "Email, Mobile, Skype, etc" %>
    <%= f.input :relevantstories, label: "LINKS TO PREVIOUS RELEVANT STORIES", hint: "*ONLY FOR OLD NEWS*, NOT THIS NEWS YOU ARE PUSHING NOW. NEVER, EVER, EVER PITCH A STORY WHICH HAS ALREADY BEEN PUBLISHED ELSEWHERE." %>
    <%= f.input :productvideos, label: "LINKS TO PRODUCT VIDEOS", hint: "" %>
    <%= f.input :crunchbase, label: "OTHER RELEVANT LINKS", hint: "LINKS TO YOUR PROFILES ON CRUNCHBASE, PRESS KIT ON DROPBOX AND TO SCREEN SHOTS OF MOBILE APP IF RELEVANT" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pitches/edit.html.erb
<h1>Editing Pitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch %> |
<%= link_to 'Back', pitches_path %>

app/views/pitches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pitches</h1>

<table>
  <thead>
    <tr>
      <th>Story</th>
      <th>Solving</th>
      <th>Personal</th>
      <th>Genesis</th>
      <th>Solved</th>
      <th>Product</th>
      <th>Nontech</th>
      <th>Traction</th>
      <th>Ux</th>
      <th>Competitors</th>
      <th>Differentiators</th>
      <th>Better</th>
      <th>Money</th>
      <th>Market</th>
      <th>Funding</th>
      <th>Total</th>
      <th>Funding</th>
      <th>Moneyusedfor</th>
      <th>Investors</th>
      <th>Team</th>
      <th>Personalstory</th>
      <th>Exclusive</th>
      <th>Embargo</th>
      <th>Contactdetails</th>
      <th>Relevantstories</th>
      <th>Productvideos</th>
      <th>Crunchbase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitches.each do |pitch| %>
      <tr>
        <td><%= pitch.story %></td>
        <td><%= pitch.solving %></td>
        <td><%= pitch.personal %></td>
        <td><%= pitch.genesis %></td>
        <td><%= pitch.solved %></td>
        <td><%= pitch.product %></td>
        <td><%= pitch.nontech %></td>
        <td><%= pitch.traction %></td>
        <td><%= pitch.ux %></td>
        <td><%= pitch.competitors %></td>
        <td><%= pitch.differentiators %></td>
        <td><%= pitch.better %></td>
        <td><%= pitch.money %></td>
        <td><%= pitch.market %></td>
        <td><%= pitch.funding %></td>
        <td><%= pitch.total %></td>
        <td><%= pitch.funding %></td>
        <td><%= pitch.moneyusedfor %></td>
        <td><%= pitch.investors %></td>
        <td><%= pitch.team %></td>
        <td><%= pitch.personalstory %></td>
        <td><%= pitch.exclusive %></td>
        <td><%= pitch.embargo %></td>
        <td><%= pitch.contactdetails %></td>
        <td><%= pitch.relevantstories %></td>
        <td><%= pitch.productvideos %></td>
        <td><%= pitch.crunchbase %></td>
        <td><%= link_to 'Show', pitch %></td>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
        <td><%= link_to 'Destroy', pitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pitch', new_pitch_path %>

app/views/pitches/new.html.erb
In July 2015, TechCrunch's Mike Butcher (<a href="http://twitter.com/mikebutcher">@MikeButcher</a>) described a template for how he wanted to be pitched by startups.</br></br>
  
This is that pitch template.</br></br>

Simply fill in the form below and you'll have an email ready to send to Mike.</br></br>

<a href="http://mbites.com/2015/07/01/the-press-release-is-dead/">Read Mike's original post here.</a></br></br>

<h4>Guidance Notes:</h4>
<ul>
  <li>No PDFs!</li>
  <li>Not all fields are required</li>
  <li>If you can tell Mike why your company rocks in one sentence then great</li>
  <li>Sure, 3 is also fine for Mike</li>
  <li>DID MIKE SAY NO PDFs? NO PDFs!!</li>
</ul>

&nbsp;

<h1>Draft a new pitch:</h1></br>

<%= render 'form' %>

<!-- <%= link_to 'Back', pitches_path %> -->

app/views/pitches/show.html.erb
<h2>What now?</h2>

Copy the pitch below into an email to your favourite TechCruch writer.</br></br>

All TechCrunch writers can be emailed on Tips@TechCrunch.com (very high traffic, but it is read). And all European writers can be email on EuroNews [@] Techcrunch.com</br></br>

If you just want Mike, he's on mike [ @ ] techcrunch.com</br></br>

<h3>A note on Subject lines and opening sentences:</h3>

Subject lines should read like headlines: “Catty, the Uber-for-Cats, Raises A $20M Seed Round” (LOL!). Opening sentence should NOT Read: “Hi Mike, How are you? It’s hot in London huh?”. It should read: “Mike, With the news that Uber has expanded into on-demand Cat Delivery, I bring you a startup that is going to BLOW those guys out of the water and this is EXCLUSIVE for you.”</br></br>

<%= link_to 'Need to edit your pitch? Click here.', edit_pitch_path(@pitch) %></br>
<%= link_to 'Want to create a new pitch? Click here.', root_path %></br>
</br>

<h2>Your Pitch</h2></br></br>

<p>
  <strong>WHAT IS THE BIG PICTURE HERE? WHAT IS ‘THE STORY’?</strong></br>
  <%= @pitch.story %>
</p>
</br></br>

<p>
  <strong>WHAT IS THE PROBLEM THIS COMPANY IS SOLVING?</strong></br>
  <%= @pitch.solving %>
</p>
</br></br>
<p>
  <strong>WAS IT A PERSONAL PROBLEM YOU HAD?</strong></br>
  <%= @pitch.personal %>
</p>
</br></br>
<p>
  <strong>DESCRIBE THE GENESIS OF THE PRODUCT</strong></br>
  <%= @pitch.genesis %>
</p>
</br></br>
<p>
  <strong>HOW HAS THIS PRODUCT SOLVED THAT PROBLEM?</strong></br>
  <%= @pitch.solved %>
</p>
</br></br>
<p>
  <strong>WHAT DOES THE PRODUCT *ACTUALLY* DO?</strong></br>
  <%= @pitch.product %>
</p>
</br></br>
<p>
  <strong>DESCRIBE IT AS IF YOU WERE DESCRIBING IT TO A NON-TECH PERSON ON THE STREET</strong></br>
  <%= @pitch.nontech %>
</p>
</br></br>
<p>
  <strong>WHAT IS HAPPENING IN THE NEWS RIGHT NOW THAT MAKES YOU RELEVANT?</strong></br>
<%= @pitch.relevance %>
</p>
</br></br>
<p>
  <strong>HOW MUCH TRACTION DO YOU HAVE?</strong></br>
  <%= @pitch.traction %>
</p>
</br></br>
<p>
  <strong>OK, NOW WALK ME THROUGH THE USER EXPERIENCE</strong></br>
  <%= @pitch.ux %>
</p>
</br></br>
<p>
  <strong>WHO ARE THE COMPETITORS?</strong></br>
  <%= @pitch.competitors %>
</p>
</br></br>
<p>
  <strong>WHAT ARE THE KEY DIFFERENTIATORS BETWEEN YOU AND OTHER PLAYERS?</strong></br>
  <%= @pitch.differentiators %>
</p>
</br></br>
<p>
  <strong>WHY IS THIS BETTER THAN THOSE OTHER GUYS?</strong></br>
  <%= @pitch.better %>
</p>
</br></br>
<p>
  <strong>HOW DO YOU MAKE (OR PLAN TO MAKE) MONEY WITH THIS?</strong></br>
  <%= @pitch.money %>
</p>
</br></br>
<p>
  <strong>HOW BIG IS THE MARKET IT IS ADDRESSING?</strong></br>
  <%= @pitch.market %>
</p>
</br></br>
<p>
  <strong>WHAT IS THE NEW ROUND OF FUNDING?</strong></br>
  <%= @pitch.funding %>
</p>
</br></br>
<p>
  <strong>HOW MUCH FUNDING (in $) DOES IT HAVE IN TOTAL?</strong></br>
  <%= @pitch.total %>
</p>
</br></br>
<p>
  <strong>WHAT WILL THE MONEY BE USED FOR?</strong></br>
  <%= @pitch.moneyusedfor %>
</p>
</br></br>
<p>
  <strong>WHO ARE THE INVESTORS?</strong></br>
  <%= @pitch.investors %>
</p>
</br>
<p>
  <strong>WHO IS IN THE TEAM?</strong></br>
  <%= @pitch.team %>
</p>
</br></br>
<p>
  <strong>DO THE FOUNDERS HAVE A COMPELLING PERSONAL STORY IN SOME WAY?</strong></br>
  <%= @pitch.personalstory %>
</p>
</br></br>
<p>
  <strong>IS THIS STORY EXCLUSIVE TO TECHCRUNCH?</strong></br>
  <%= @pitch.exclusive %>
</p>
</br></br>
<p>
  <strong>IF NOT, WHEN DOES THE EMBARGO DROP?</strong></br>
  <%= @pitch.embargo %>
</p>
</br></br>
<p>
  <strong>CONTACT DETAILS FOR FOUNDERS</strong></br>
  <%= @pitch.contactdetails %>
</p>
</br></br>
<p>
  <strong>LINKS TO PREVIOUS RELEVANT STORIES</strong></br>
  <%= @pitch.relevantstories %>
</p>
</br></br>
<p>
  <strong>LINKS TO PRODUCT VIDEOS</strong></br>
  <%= @pitch.productvideos %>
</p>
</br></br>
<p>
  <strong>OTHER RELEVANT LINKS</strong></br>
  <%= @pitch.crunchbase %>
</p>
</br></br>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>